title: ADR JS
logo: https://raw.githubusercontent.com/Virtualix-LTD/adrjs/refs/heads/master/docs/assets/logo.svg
description: Adrhitecture Decision Records for npx.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
