title: ADR JS
logo: https://raw.githubusercontent.com/Virtualix-LTD/adrjs/refs/heads/master/docs/assets/logo.svg
description: Architecture Decision Records for npx.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
github:
  npmjs_url: https://www.npmjs.com/package/adrjs
